localization_2d_node:
  ros__parameters:
    sensors:
      lidar:
        topic: "/scan"
        enabled: true
      imu:
        topic: "/imu/data"
        enabled: true
      odom:
        topic: "/odom"
        enabled: true
    
    local_map_builder:
      use_online_correlative_scan_matching: true

      real_time_correlative_scan_matcher:
        linear_search_window: 0.1
        angular_search_window: 5.0
        translation_delta_cost_weight: 10.0
        rotation_delta_cost_weight: 0.1

      motion_filter:
        max_time_seconds: 5.0
        max_distance: 0.2
        max_angle: 5.0

    pose_graph:
      optimize_every_nodes: 10
      max_node_buffer_length: 40
      min_global_localization_score: 0.3
      min_relocalization_score: 0.3
      min_tracking_score: 0.3

      real_time_correlative_scan_matcher:
        linear_search_window: 0.1
        angular_search_window: 5.0
        translation_delta_cost_weight: 10.0
        rotation_delta_cost_weight: 0.1

      fast_correlative_scan_matcher:
        linear_search_window: 8.0
        angular_search_window: 30.0
        branch_and_bound_depth: 7